sudo: required
dist: trusty
language: node_js

addons:
  chrome: stable
  yarn: stable

git:
  depth: 1

cache:
  npm: true
  yarn: true
  directories:
    - ./node_modules/

before_install:
  - export NG_CLI_ANALYTICS=ci
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

jobs:
  include:
    - stage: pre
      env: 'TASK=build_artifacts'
    - stage: test
      env: 'TASK=test'
    - stage: test
      env: 'TASK=lint'
    - stage: test
      env: 'TASK=site:build'
    - stage: test
      env: 'TASK=build'
    - stage: test
      env: 'TASK=test:cli'

stages:
  - name: pre
    if: branch = master
  - name: test
    if: branch = master

install:
  - chmod +x -R scripts
  - yarn

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
